project_id = "ygxbcjxyqcbuozydimiq"

[functions.create-quote-request]
verify_jwt = true

[functions.expire-quote-request]
verify_jwt = true

[functions.promote-next-business]
verify_jwt = true

[functions.respond-quotation]
verify_jwt = true

[functions.cakto-webhook]
verify_jwt = false

[functions.cakto-subscription]
enabled = true
verify_jwt = false
entrypoint = "./functions/cakto-subscription/index.ts"
