import Link from "next/link";

const sections = [
  ["O que é o CotaMap", "O CotaMap é uma plataforma tecnológica que aproxima clientes, que solicitam cotações, e empresas ou lojistas, que podem visualizar solicitações disponíveis e enviar propostas. O CotaMap não é vendedor das peças e não substitui a negociação entre as partes."],
  ["Cadastro e responsabilidades", "Cada usuário deve fornecer informações verdadeiras, manter seus dados atualizados e proteger suas credenciais. O titular da conta é responsável pelo uso realizado com seu acesso."],
  ["Solicitações e cotações", "O cliente é responsável pelas informações inseridas na solicitação. A empresa ou lojista é responsável pelas propostas que envia, incluindo preço, disponibilidade, prazo e observações. A escolha de uma cotação é feita pelo cliente conforme as opções apresentadas."],
  ["Planos para empresas", "Os planos Free e Premium são destinados a empresas ou lojistas. O cliente final não precisa contratar plano para solicitar cotações. O Premium é uma assinatura para lojistas, sujeita às condições apresentadas no momento da contratação."],
  ["Uso permitido", "É proibido usar a plataforma para fraude, informações falsas, assédio, tentativa de acesso indevido, automação abusiva ou qualquer finalidade ilegal. Contas podem ser suspensas ou encerradas em caso de abuso, fraude ou violação destes termos."],
  ["Disponibilidade e responsabilidades", "Buscamos manter o serviço disponível, mas podem ocorrer manutenções, indisponibilidades ou falhas de fornecedores. O CotaMap não garante a qualidade, entrega, garantia ou negociação realizada entre cliente e lojista, que permanecem responsáveis por suas próprias relações."],
  ["Propriedade intelectual e alterações", "A marca, os componentes e os conteúdos do CotaMap são protegidos pela legislação aplicável. Podemos atualizar funcionalidades e estes termos, publicando a versão vigente nesta página."],
] as const;

export default function TermsPage() { return <main className="min-h-screen bg-[#F3F4F6] px-5 py-12 text-[#111827] sm:px-8 sm:py-16"><article className="mx-auto max-w-3xl rounded-[2rem] bg-white p-7 shadow-sm sm:p-12"><Link href="/" className="text-sm font-bold text-[#F97316]">← Voltar ao CotaMap</Link><p className="mt-10 text-xs font-black uppercase tracking-[0.2em] text-[#F97316]">CotaMap</p><h1 className="mt-3 text-4xl font-black tracking-[-0.04em] sm:text-5xl">Termos de Uso</h1><p className="mt-4 text-sm text-black/55">Última atualização: 13 de agosto de 2026</p><p className="mt-8 leading-7 text-black/70">Ao utilizar o CotaMap, você concorda com estes termos e com o uso responsável da plataforma.</p><div className="mt-10 space-y-8">{sections.map(([title,body])=><section key={title}><h2 className="text-xl font-black">{title}</h2><p className="mt-2 leading-7 text-black/65">{body}</p></section>)}</div><p className="mt-10 border-t border-black/10 pt-6 text-sm leading-6 text-black/55">Contato: contato@cotamap.com.br.</p></article></main>; }
