import Link from "next/link";

const sections = [
  ["Dados que podemos receber", "Podemos receber dados informados no cadastro, como nome e e-mail, telefone quando utilizado, dados da empresa ou loja e informações fornecidas em solicitações de cotação. Também podemos tratar imagens enviadas em chamados e informações técnicas necessárias para autenticação, segurança e funcionamento da plataforma."],
  ["Como usamos os dados", "Usamos essas informações para criar e proteger contas, operar solicitações e cotações, aproximar clientes e empresas participantes, permitir o acompanhamento de pedidos, prestar suporte e manter a segurança e a disponibilidade do CotaMap."],
  ["Compartilhamento necessário", "Para que uma cotação funcione, compartilhamos com as empresas participantes as informações necessárias da solicitação. Quando uma proposta é escolhida, o contato necessário para a continuidade do atendimento pode ser disponibilizado conforme o funcionamento da plataforma. Não vendemos dados pessoais."],
  ["Autenticação, segurança e armazenamento", "Adotamos controles técnicos e administrativos compatíveis com o serviço. Os dados são armazenados em fornecedores de infraestrutura necessários à operação, incluindo serviços de autenticação, banco de dados, armazenamento e hospedagem. O acesso é limitado conforme a finalidade e as permissões da conta."],
  ["Pagamentos dos lojistas", "Assinaturas e pagamentos de empresas ou lojistas podem ser processados por plataformas de pagamento integradas. O tratamento realizado por esses fornecedores também segue as políticas e condições próprias deles."],
  ["Direitos do titular", "Nos termos da legislação aplicável, especialmente da LGPD, você pode solicitar informações sobre o tratamento, correção ou exclusão de dados quando legalmente possível. Para solicitações, entre em contato pelo e-mail contato@cotamap.com.br."],
  ["Retenção e alterações", "Mantemos os dados pelo período necessário ao funcionamento do serviço, cumprimento de obrigações legais, segurança e exercício regular de direitos. Esta política pode ser atualizada para refletir mudanças no serviço ou na legislação, com a versão vigente publicada nesta página."],
] as const;

export default function PrivacyPolicyPage() { return <main className="min-h-screen bg-[#F3F4F6] px-5 py-12 text-[#111827] sm:px-8 sm:py-16"><article className="mx-auto max-w-3xl rounded-[2rem] bg-white p-7 shadow-sm sm:p-12"><Link href="/" className="text-sm font-bold text-[#F97316]">← Voltar ao CotaMap</Link><p className="mt-10 text-xs font-black uppercase tracking-[0.2em] text-[#F97316]">CotaMap</p><h1 className="mt-3 text-4xl font-black tracking-[-0.04em] sm:text-5xl">Política de Privacidade</h1><p className="mt-4 text-sm text-black/55">Última atualização: 13 de agosto de 2026</p><p className="mt-8 leading-7 text-black/70">Esta política explica, de forma clara, como o CotaMap trata informações necessárias para conectar clientes e empresas em solicitações de cotação de autopeças.</p><div className="mt-10 space-y-8">{sections.map(([title,body])=><section key={title}><h2 className="text-xl font-black">{title}</h2><p className="mt-2 leading-7 text-black/65">{body}</p></section>)}</div><p className="mt-10 border-t border-black/10 pt-6 text-sm leading-6 text-black/55">Dúvidas ou solicitações: contato@cotamap.com.br.</p></article></main>; }
