"use client";
import { useMutation, useQuery, useQueryClient } from "@tanstack/react-query";
import { BusinessShell } from "@/features/business/components/business-shell";
import { getBusinessRegistration, updateBusinessHours, type BusinessRegistration } from "@/services/business/registration-service";

const days = [["mon", "Segunda-feira"], ["tue", "Terça-feira"], ["wed", "Quarta-feira"], ["thu", "Quinta-feira"], ["fri", "Sexta-feira"], ["sat", "Sábado"], ["sun", "Domingo"]] as const;
type Hours = BusinessRegistration["openingHours"];
const defaults = (): Hours => Object.fromEntries(days.map(([key]) => [key, { enabled: key !== "sun", open: "08:00", close: "18:00" }])) as Hours;
export default function BusinessHoursPage() { const client = useQueryClient(); const query = useQuery({ queryKey: ["business-registration"], queryFn: getBusinessRegistration }); const mutation = useMutation({ mutationFn: updateBusinessHours, onSuccess: () => void client.invalidateQueries({ queryKey: ["business-registration"] }) }); const hours = query.data?.openingHours && Object.keys(query.data.openingHours).length ? query.data.openingHours : defaults(); return <BusinessShell><section className="mx-auto max-w-3xl"><p className="text-xs font-black uppercase tracking-[0.16em] text-[#F97316]">Empresa</p><h1 className="mt-3 text-4xl font-black">Horário de funcionamento</h1><p className="mt-3 text-black/55">Sua loja só recebe chamados enquanto estiver aberta.</p>{query.isLoading ? <p className="mt-8">Carregando...</p> : <form onSubmit={(e) => { e.preventDefault(); const form = new FormData(e.currentTarget); const next = Object.fromEntries(days.map(([key]) => [key, { enabled: form.get(`${key}-enabled`) === "on", open: String(form.get(`${key}-open`) ?? "08:00"), close: String(form.get(`${key}-close`) ?? "18:00") }])) as Hours; mutation.mutate(next); }} className="mt-8 space-y-3 rounded-3xl bg-white p-6 shadow-sm">{days.map(([key, label]) => { const day = hours[key] ?? { enabled: false, open: "08:00", close: "18:00" }; return <div key={key} className="grid items-center gap-3 rounded-2xl bg-[#F8FAFC] p-4 sm:grid-cols-[1fr_auto_auto]"><label className="flex items-center gap-3 font-bold"><input name={`${key}-enabled`} type="checkbox" defaultChecked={day.enabled} />{label}</label><label className="text-xs font-bold text-black/55">Abre<input name={`${key}-open`} type="time" defaultValue={day.open} className="ml-2 rounded-lg border p-2 text-sm text-black" /></label><label className="text-xs font-bold text-black/55">Fecha<input name={`${key}-close`} type="time" defaultValue={day.close} className="ml-2 rounded-lg border p-2 text-sm text-black" /></label></div>})}<button disabled={mutation.isPending} className="w-full rounded-xl bg-[#F97316] p-4 font-black text-white">{mutation.isPending ? "Salvando..." : "Salvar horários"}</button>{mutation.isSuccess ? <p role="status" className="text-sm text-emerald-700">Horários salvos.</p> : null}{mutation.error ? <p role="alert" className="text-sm text-red-700">Não foi possível salvar os horários. Tente novamente.</p> : null}</form>}</section></BusinessShell>; }
