"use client";

import { BarChart3, CheckCircle2, Clock3, Search, XCircle } from "lucide-react";
import { useQuery } from "@tanstack/react-query";
import { useMemo, useState } from "react";
import { BusinessShell } from "@/features/business/components/business-shell";
import { getCurrentBusinessId } from "@/services/business/business-service";
import { createClient } from "@/lib/supabase/client";

type Period = "today" | "week" | "month";
const statusLabel = (status: string) => ({ sent: "Enviada", accepted: "Aceita", rejected: "Recusada", expired: "Expirada", pending: "Em análise" }[status] ?? status);

export default function BusinessQuotationsPage() {
  const [period, setPeriod] = useState<Period>("today"); const [status, setStatus] = useState("all"); const [search, setSearch] = useState("");
  const query = useQuery({ queryKey: ["business-quotations"], queryFn: async () => { const businessId = await getCurrentBusinessId(); const { data, error } = await createClient().from("quotations").select("id,quote_request_id,business_id,amount,brand,notes,status,created_at").eq("business_id", businessId).order("created_at", { ascending: false }); if (error) throw error; return data; } });
  const filtered = useMemo(() => { const start = new Date(); if (period === "today") start.setHours(0,0,0,0); else if (period === "week") start.setDate(start.getDate()-7); else start.setMonth(start.getMonth()-1); return (query.data ?? []).filter((item) => new Date(item.created_at) >= start && (status === "all" || item.status === status) && (!search.trim() || `${item.brand ?? ""} ${item.notes ?? ""}`.toLowerCase().includes(search.toLowerCase()))); }, [period,query.data,search,status]);
  return <BusinessShell><header className="mb-8 rounded-[2rem] border border-orange-100 bg-white p-6 shadow-[0_12px_40px_rgba(15,23,42,.05)] sm:p-8"><div className="flex items-center gap-2 text-xs font-black uppercase tracking-[0.18em] text-orange-500"><BarChart3 className="size-4" /> Resultados da operação</div><h1 className="mt-3 text-3xl font-black tracking-[-0.04em] text-slate-900 sm:text-4xl">Minhas cotações</h1><p className="mt-2 text-sm text-slate-500">Acompanhe suas propostas e encontre as oportunidades mais quentes.</p></header><div className="mb-6 grid gap-3 rounded-[1.5rem] border border-slate-200/80 bg-white p-4 shadow-sm sm:grid-cols-3"><select value={period} onChange={(e)=>setPeriod(e.target.value as Period)} className="rounded-xl border border-slate-200 p-3 text-sm font-bold"><option value="today">Hoje</option><option value="week">Semana</option><option value="month">Mês</option></select><select value={status} onChange={(e)=>setStatus(e.target.value)} className="rounded-xl border border-slate-200 p-3 text-sm font-bold"><option value="all">Todos os status</option><option value="sent">Enviadas</option><option value="accepted">Aceitas</option><option value="rejected">Recusadas</option><option value="expired">Expiradas</option></select><label className="flex items-center gap-2 rounded-xl border border-slate-200 px-3"><Search className="size-4 text-slate-400" /><input value={search} onChange={(e)=>setSearch(e.target.value)} placeholder="Pesquisar por peça" className="min-w-0 flex-1 p-3 text-sm outline-none" /></label></div>{query.isLoading ? <State text="Carregando cotações..." /> : query.error ? <State text="Não foi possível carregar suas cotações." /> : !filtered.length ? <State text="Nenhuma cotação enviada." /> : <ul className="grid gap-4 md:grid-cols-2">{filtered.map((q)=><li key={q.id} className="rounded-[2rem] border border-slate-200/80 bg-white p-6 shadow-[0_12px_40px_rgba(15,23,42,.06)]"><div className="flex items-start justify-between gap-4"><div><span className="text-xs font-black uppercase tracking-wider text-orange-500">Proposta enviada</span><p className="mt-2 text-3xl font-black text-slate-900">R$ {Number(q.amount).toLocaleString("pt-BR",{minimumFractionDigits:2})}</p></div><Status status={q.status} /></div><p className="mt-5 rounded-2xl bg-slate-50 p-4 text-sm text-slate-600">{q.brand ?? "Marca não informada"} · {q.notes ?? "Sem observações"}</p><time className="mt-4 flex items-center gap-2 text-xs font-bold text-slate-400"><Clock3 className="size-4" />{new Date(q.created_at).toLocaleString("pt-BR")}</time></li>)}</ul>}</BusinessShell>;
}
function Status({status}:{status:string}) { const Icon=status==="accepted"?CheckCircle2:status==="rejected"?XCircle:Clock3; return <span className={`inline-flex items-center gap-1.5 rounded-full px-3 py-1.5 text-xs font-black ${status==="accepted"?"bg-emerald-50 text-emerald-700":status==="rejected"?"bg-red-50 text-red-700":"bg-amber-50 text-amber-700"}`}><Icon className="size-4"/>{statusLabel(status)}</span>; }
function State({ text }: { text: string }) { return <div className="rounded-[2rem] border border-dashed border-slate-300 bg-white p-12 text-center text-sm font-semibold text-slate-500">{text}</div>; }
