"use client";
import Link from "next/link";
import { useMutation, useQuery, useQueryClient } from "@tanstack/react-query";
import { useMemo, useState } from "react";
import { BusinessShell } from "@/features/business/components/business-shell";
import { getEmployees, removeEmployee, resetEmployeePin } from "@/services/business/employee-service";

export default function EmployeesPage() {
  const queryClient = useQueryClient(); const employees = useQuery({ queryKey: ["business-employees-admin"], queryFn: getEmployees });
  const [search, setSearch] = useState(""); const [filter, setFilter] = useState("all"); const [temporaryPin, setTemporaryPin] = useState<string | null>(null);
  const reset = useMutation({ mutationFn: resetEmployeePin, onSuccess: setTemporaryPin }); const remove = useMutation({ mutationFn: removeEmployee, onSuccess: () => void queryClient.invalidateQueries({ queryKey: ["business-employees-admin"] }) });
  const filtered = useMemo(() => (employees.data ?? []).filter((employee) => `${employee.name} ${employee.role} ${employee.presenceStatus}`.toLowerCase().includes(search.toLowerCase())).filter((employee) => filter === "all" || (filter === "active" && employee.isActive) || (filter === "inactive" && !employee.isActive) || (filter === employee.role) || (filter === employee.presenceStatus)), [employees.data, filter, search]);
  return <BusinessShell><div className="flex flex-wrap items-end justify-between gap-4"><div><p className="text-xs font-black uppercase tracking-[0.16em] text-[#F97316]">Equipe</p><h1 className="mt-3 text-4xl font-black tracking-[-0.04em]">Funcionários</h1></div><Link href="/empresa/funcionarios/novo" className="rounded-xl bg-[#F97316] px-4 py-3 text-sm font-bold text-white">Novo funcionário</Link></div><div className="my-6 flex flex-wrap gap-3"><input aria-label="Pesquisar funcionários" value={search} onChange={(event) => setSearch(event.target.value)} placeholder="Pesquisar nome ou cargo" className="min-w-64 rounded-xl border bg-white px-4 py-3 text-sm"/><select aria-label="Filtrar funcionários" value={filter} onChange={(event) => setFilter(event.target.value)} className="rounded-xl border bg-white px-4 py-3 text-sm"><option value="all">Todos</option><option value="active">Ativos</option><option value="inactive">Inativos</option><option value="online">Online</option><option value="offline">Offline</option><option value="manager">Managers</option><option value="employee">Employees</option></select></div>{temporaryPin ? <div role="alert" className="mb-5 rounded-xl bg-emerald-50 p-4 text-sm">PIN temporário (exiba uma única vez): <strong>{temporaryPin}</strong><button className="ml-4 underline" onClick={() => setTemporaryPin(null)}>Ocultar</button></div> : null}{employees.isLoading ? <p>Carregando equipe...</p> : employees.error ? <p role="alert">Não foi possível carregar os funcionários.</p> : filtered.length === 0 ? <p className="rounded-2xl bg-white p-8 text-center">Nenhum funcionário encontrado.</p> : <div className="grid gap-4">{filtered.map((employee) => <article key={employee.id} className="rounded-2xl bg-white p-5 shadow-sm"><div className="flex flex-wrap items-center justify-between gap-4"><div><Link href={`/empresa/funcionarios/${employee.id}`} className="text-lg font-black hover:text-[#F97316]">{employee.name}</Link><p className="text-sm text-black/55">{employee.role} · {employee.isActive ? "Ativo" : "Inativo"} · {employee.presenceStatus}</p><p className="mt-1 text-xs text-black/45">Último acesso: {employee.lastAccessAt ? new Date(employee.lastAccessAt).toLocaleString("pt-BR") : "Sem dados"}</p></div><div className="flex gap-2"><button onClick={() => reset.mutate(employee.id)} disabled={reset.isPending} className="rounded-lg border px-3 py-2 text-xs font-bold">Resetar PIN</button><button onClick={() => { if (window.confirm("Remover o vínculo deste funcionário?")) remove.mutate(employee.id); }} disabled={remove.isPending || employee.role === "owner"} className="rounded-lg border border-red-200 px-3 py-2 text-xs font-bold text-red-600">Remover</button></div></div></article>)}</div>}</BusinessShell>;
}
