import type { QuoteComparison } from "@/features/quotes/comparison/quote-types";

export const simulatedQuotes: readonly QuoteComparison[] = [
  {
    id: "silva",
    businessName: "Auto Peças Silva",
    businessInitials: "AS",
    rating: 4.9,
    reviewCount: 328,
    cotamapScore: 97,
    price: 189.9,
    brand: "Bosch",
    note: "Produto original com garantia de 90 dias.",
    description:
      "Pastilha de freio dianteira Bosch, jogo completo para o eixo dianteiro. Produto novo, lacrado e com nota fiscal.",
    distanceKm: 2.4,
    pickupMinutes: 25,
    pickupLabel: "25 minutos",
    responseMinutes: 3,
    status: "Pronta",
    address: "Av. Brasil, 1240 — Centro",
    openingHours: "Hoje, até 18h30",
    paymentMethods: ["Pix", "Crédito", "Débito"],
    imagePosition: "78% 24%",
  },
  {
    id: "centro",
    businessName: "Centro Auto Parts",
    businessInitials: "CA",
    rating: 4.8,
    reviewCount: 214,
    cotamapScore: 94,
    price: 174.5,
    brand: "TRW",
    note: "Excelente custo-benefício e pronta retirada.",
    description:
      "Jogo de pastilhas TRW com certificação e garantia do fabricante. Compatibilidade conferida pela equipe da loja.",
    distanceKm: 4.1,
    pickupMinutes: 15,
    pickupLabel: "15 minutos",
    responseMinutes: 5,
    status: "Separando",
    address: "Rua das Oficinas, 88 — Jardim América",
    openingHours: "Hoje, até 19h",
    paymentMethods: ["Pix", "Crédito em 3x", "Dinheiro"],
    imagePosition: "72% 58%",
  },
  {
    id: "parana",
    businessName: "Paraná Auto Peças",
    businessInitials: "PA",
    rating: 5,
    reviewCount: 96,
    cotamapScore: 99,
    price: 218,
    brand: "Cobreq",
    note: "Linha premium com baixo ruído e alta durabilidade.",
    description:
      "Pastilha Cobreq linha premium, formulada para reduzir ruídos e oferecer frenagem progressiva no uso urbano.",
    distanceKm: 6.8,
    pickupMinutes: 45,
    pickupLabel: "45 minutos",
    responseMinutes: 2,
    status: "Pronta",
    address: "Av. Paraná, 510 — Zona Norte",
    openingHours: "Hoje, até 18h",
    paymentMethods: ["Pix", "Crédito", "Débito", "Dinheiro"],
    imagePosition: "65% 42%",
  },
  {
    id: "motorcar",
    businessName: "MotorCar Peças",
    businessInitials: "MP",
    rating: 4.7,
    reviewCount: 441,
    cotamapScore: 91,
    price: 165,
    brand: "Fras-le",
    note: "Disponível no centro de distribuição.",
    description:
      "Jogo dianteiro Fras-le. A loja solicitará a transferência para a unidade antes da retirada pelo cliente.",
    distanceKm: 8.3,
    pickupMinutes: 180,
    pickupLabel: "Até 3 horas",
    responseMinutes: 7,
    status: "Sob encomenda",
    address: "Rua do Contorno, 340 — Industrial",
    openingHours: "Hoje, até 20h",
    paymentMethods: ["Pix", "Crédito em 6x"],
    imagePosition: "80% 74%",
  },
  {
    id: "avenida",
    businessName: "Avenida Auto Center",
    businessInitials: "AA",
    rating: 4.6,
    reviewCount: 187,
    cotamapScore: 89,
    price: 196.75,
    brand: "Bosch",
    note: "Retirada rápida no balcão exclusivo do CotaMap.",
    description:
      "Pastilha Bosch com procedência e garantia. Pedido separado em balcão rápido após a confirmação da escolha.",
    distanceKm: 1.7,
    pickupMinutes: 35,
    pickupLabel: "35 minutos",
    responseMinutes: 4,
    status: "Separando",
    address: "Av. Principal, 2300 — Vila Nova",
    openingHours: "Hoje, até 19h30",
    paymentMethods: ["Pix", "Crédito", "Débito"],
    imagePosition: "76% 34%",
  },
] as const;
