"use client";
import Link from "next/link";
import { useParams, useRouter } from "next/navigation";
import { useEffect, useState } from "react";
import { useMutation, useQueryClient } from "@tanstack/react-query";
import { BusinessShell } from "@/features/business/components/business-shell";
import { CallResponseForm } from "@/features/business/components/call-response-form";
import { useBusinessCallStatus, useBusinessCalls } from "@/features/business/hooks/use-business-calls";
import { getCurrentBusinessId, respondToQuotation } from "@/services/business/business-service";
function friendlyCallError(error: unknown) { const message = error instanceof Error ? error.message : ""; if (message.includes("request_expired") || message.includes("request_not_waiting")) return "Este chamado já foi encerrado pelo cliente."; if (message.includes("notification_not_active") || message.includes("notification_not_found")) return "Este chamado já não está disponível para resposta."; return "Não foi possível responder a este chamado. Tente novamente."; }
export default function BusinessCallDetailsPage() {
  const params = useParams<{ id: string }>(); const router = useRouter(); const calls = useBusinessCalls(); const status = useBusinessCallStatus(params.id); const queryClient = useQueryClient(); const [responding, setResponding] = useState(false); const [errorMessage, setErrorMessage] = useState<string | null>(null); const call = calls.data?.find((item) => item.notification.id === params.id); const terminal = status.data == null || status.data.requestStatus !== "waiting" || !["pending", "sent"].includes(status.data.notificationStatus);
  useEffect(() => { if (!calls.isLoading && !status.isLoading && terminal) router.replace("/empresa/chamados"); }, [calls.isLoading, router, status.isLoading, terminal]);
  const reject = useMutation({ mutationFn: async () => respondToQuotation({ notificationId: params.id, businessId: await getCurrentBusinessId(), action: "reject" }), onSuccess: async () => { await queryClient.invalidateQueries({ queryKey: ["business-calls"] }); }, onError: (error: Error) => setErrorMessage(error.message) });
  if (calls.isLoading || status.isLoading) return <BusinessShell><p>Verificando chamado...</p></BusinessShell>;
  if (terminal || !call) return <BusinessShell><p className="rounded-2xl bg-white p-8">Este chamado foi encerrado pelo cliente. Voltando para chamados ativos...</p></BusinessShell>;
  const closed = call.notification.status !== "pending" && call.notification.status !== "sent";
  return <BusinessShell><Link href="/empresa/chamados" className="inline-flex items-center rounded-xl border border-orange-200 bg-white px-4 py-2 text-sm font-black text-orange-600 shadow-sm">← Voltar aos chamados</Link><div className="mt-6 grid gap-6 lg:grid-cols-[1fr_0.8fr]"><section className="rounded-[2rem] border border-slate-200/80 bg-white p-6 shadow-sm sm:p-8"><p className="text-xs font-black uppercase tracking-[0.16em] text-orange-500">Detalhes do chamado</p><h1 className="mt-3 text-3xl font-black">{call.request.part_name ?? call.request.description}</h1><p className="mt-4 text-sm text-black/60">{[call.request.vehicle_brand, call.request.vehicle_model, call.request.vehicle_year, call.request.vehicle_engine].filter(Boolean).join(" · ") || "Veículo não informado"}</p><div className="mt-6 space-y-2">{call.items.length ? call.items.map((item) => <div key={item.id} className="rounded-xl bg-black/[.03] p-3"><strong>{item.name}</strong><span className="ml-2 text-sm text-black/60">× {item.quantity}{item.brand ? ` · ${item.brand}` : ""}</span></div>) : null}</div><p className="mt-5 text-sm leading-6 text-black/65">{call.request.observation ?? "Sem observações."}</p>{call.images?.length ? <div className="mt-6 grid gap-3 sm:grid-cols-2">{call.images.map((image) => <a key={image.url} href={image.url} target="_blank" rel="noreferrer"><img src={image.url} alt={image.fileName ?? "Foto enviada pelo cliente"} className="aspect-[4/3] w-full rounded-2xl object-cover" /></a>)}</div> : null}<div className="mt-8 grid min-h-40 place-items-center rounded-2xl bg-[#F3F4F6] text-sm font-semibold text-black/40">Localização do chamado</div><div className="mt-4 rounded-2xl bg-[#F3F4F6] p-4 text-sm font-bold">{closed ? "Solicitação encerrada." : `Expira em ${call.notification.expires_at ? new Date(call.notification.expires_at).toLocaleTimeString("pt-BR") : "breve"}`}</div></section>{responding ? <CallResponseForm notificationId={params.id} businessId={call.notification.business_id} items={call.items} /> : <section className="rounded-[2rem] border border-orange-100 bg-white p-6 shadow-sm sm:p-8"><p className="text-xs font-black uppercase tracking-[0.18em] text-orange-500">Ação rápida</p><h2 className="mt-2 text-2xl font-black">Responder ao cliente</h2>{errorMessage ? <p className="mt-4 rounded-2xl bg-orange-50 p-4 text-sm text-orange-800">{friendlyCallError(new Error(errorMessage))}</p> : null}<div className="mt-6 grid gap-3"><button type="button" disabled={closed || reject.isPending} onClick={() => setResponding(true)} className="min-h-12 rounded-xl bg-orange-500 px-5 text-sm font-black uppercase text-white disabled:opacity-50">Aceitar</button><button type="button" disabled={closed || reject.isPending} onClick={() => reject.mutate()} className="min-h-12 rounded-xl border border-black/10 px-5 text-sm font-black uppercase disabled:opacity-50">{reject.isPending ? "Recusando..." : "Recusar"}</button></div></section>}</div></BusinessShell>;
}
